### PR TITLE
style: fix mobile view of bulletin

### LINKED ISSUE #99: [最新公告] rwd排列方式錯誤
## Description
1.最新公告的 rwd 為兩個一排，現在為一個一排
image
2. rwd 最新公告 title大小為 ２６px
3. 卡片裡的title要與上面的邊界距離35px (padding加大）
4. 卡片裡的按鈕 thickness為３
image

## Steps to Reproduce

1. Go to index
2. See error

## Expected Behavior
image

## Actual Behavior

1.最新公告的 rwd 為兩個一排，現在為一個一排
image
2. rwd 最新公告 title大小為 ２６px
3. 卡片裡的title要與上面的邊界距離35px (padding加大）
image

## More Information
可以到figma的rwd page觀看細節
https://www.figma.com/file/1za4uYNpSonvgxdcLoHAzs/PyCon-Taiwan-2021-Web?node-id=1875%3A3945

### PR DESCRIPTION
**Pull request by mattwang44**
## Types of Changes

- [x] **Bugfix**
- [ ] **New feature**
- [ ] **Refactoring**
- [ ] **Breaking change** (any change that would cause existing functionality to not work as expected)
- [ ] **Documentation Update**
- [ ] **Other (please describe)**

## Description
close #99 

### Preview

https://user-images.githubusercontent.com/24987826/125151694-919a4b80-e17a-11eb-83e6-f7718ca5e767.mp4

<details>
<summary> web view</summary>

</details>
<details>
<summary> iPad pro</summary>

</details>
<details>
<summary> iPad</summary>

</details>
<details>
<summary>iPhone 6/7/8 plus</summary>

</details>
<details>
<summary> iPhone 6/7/8</summary>

</details>
<details>
<summary> iPhone 5/SE</summary>

</details>

### CODE REVIEW

File: components/bulletins/BulletinCard.vue [hunk 1]
```diff
@@ -55,7 +55,8 @@ export default {
 
 <style lang="postcss" scoped>
 .bulletinCard {
-    @apply relative flex flex-col items-center font-serif rounded-3xl border-4;
+    @apply relative flex flex-col items-center font-serif rounded-3xl;
+    border-width: 3px;
```
Comment (yuyanghh) [inline components/bulletins/BulletinCard.vue:59]: Sorry for the misinterpretation.
In smaller screen the border with is 3px and in bigger screen the border width enlarges to 4px.

**Comment by yuyanghh** [comment]
LGTM 🎉
