### PR TITLE
style: fix bulletin card based on design spec

### LINKED ISSUE #127: [最新公告] card的style修改
## Description
1.最新公告card 寬為214
2.card外圍thickness為４
3.card裡面按鈕的thickness為３
4.最新公告標題字重為Bold
5.防疫守則的『閱讀』按鈕，改為『前往閱讀』
image

## Steps to Reproduce

1. Go to index
2. Scroll down to 最新公告
３. See error

## Expected Behavior

1.最新公告card 寬為214
2.card外圍thickness為４
3.card裡面按鈕的thickness為３
4.最新公告標題字重為Bold
5.防疫守則的『閱讀』按鈕，改為『前往閱讀』
image

### PR DESCRIPTION
**Pull request by linooohon**
## Types of changes

* **Bugfix**

#### Fixed all problems(1st ~ 5th) which are mentioned in #127 .
1. Changed card width to 214px in `BulletinCard.vue` 
-> Solved `1st` in the issue's Expected Behavior.
2. Added `font-bold` in `BulletinCard.vue`.
-> Solved `4th` in the issue's Expected Behavior.
3. Changed「閱讀」to「前往閱讀」in `BulletinCard.i18n.js` .
-> Solved `5th` in the issue's Expected Behavior.
---
4. For `2nd` and `3rd` which are mentioned in the issue's Expected Behavior. (Design Team wanted the border-width to always be 4px on the cards, and to always be 3px on the button.). So,
    - I remained `border-4` in `BulletinCard.vue` to solve `2nd`.
    - Added `bulletin props` to solve `3rd`.
 -> Solved `2nd` & `3rd` in the issue's Expected Behavior.

## More Detail for this PR
1. On mobile view, `justify-start` caused the whole section isn't in the center position, I change it to `justify-center`. But since we need to have five-card in one row on the desktop view now, I still remained `lg:justify-start` which will be applied on Desktop view.
2. And also in this PR, I make `<LandingH2.vue>` components, for the subtitle of each section on the home page, to make it more structured and reasonable.

## Steps to Test This Pull Request
- Go to the home page's bulletin section.

Screen Shot 2021-08-18 at 8 39 53 AM

## Related Issue
Fixed #127

### CODE REVIEW

**Comment by flynnhou** [comment]
@linooohon Could you provide more context on the PR descriptions so that we know what things you've fixed instead of only referring to the issue? As far I could tell, this PR only addressed a part of the issue #127, meaning not everything has been fixed.

**Comment by linooohon** [comment]
Hi @flynnhou , I added more description on this PR.

**Comment by mattwang44** [comment]
Rebase to latest main and add a commit for adding a card linked to job listing page.

File: components/core/titles/LandingH2.vue [hunk 1]
```diff
@@ -0,0 +1,40 @@
+<template>
+    <div class="flex justify-center">
+        <h2 :class="classObject">{{ subTitle }}</h2>
+    </div>
+</template>
+
+<script>
+export default {
+    name: 'LandingH2',
```
Comment (flynnhou) [inline components/core/titles/LandingH2.vue:9]: This doesn't require any changes, but I personally would rename this component with a general term such as "CoreH2".

File: components/core/titles/LandingH2.vue [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+    props: {
+        subTitle: {
```
Comment (flynnhou) [inline components/core/titles/LandingH2.vue:11]: Did you mean `subtitle` instead of `subTitle`? Normally, when there already exists a `title` prop/variable, the `subtitle` is therefore meaningful. Having `title` and `subtitle` implies subordination and that the former is more important than the latter.

Hence, in this case, because this component only contains one prop to define the texts of h2, I would suggest that this prop is simply named `title`.

**Review by flynnhou — COMMENTED** [review]
Everything works perfectly, and there's only a few nitpicking stuff to consider modifying.

**Review by flynnhou — APPROVED** [review]
lgtm

File: pages/index.vue [hunk 3]
```diff
@@ -48,17 +48,13 @@
...
-            <h1 class="bulletin-title">{{ $t('bulletinList') }}</h1>
+        <div class="bulletin-section">
+            <core-h2 :sub-title="$t('bulletinList')" bulletin-color></core-h2>
             <bulletin-card-collection></bulletin-card-collection>
-        </i18n-page-wrapper>
+        </div>
 
         <div class="intro-section">
-            <h2 class="intro-title">{{ $t('pyconIntro') }}</h2>
+            <core-h2 :sub-title="$t('pyconIntro')"></core-h2>
```
Comment (flynnhou) [inline pages/index.vue:57]:
```suggestion
            <core-h2 :title="$t('pyconIntro')"></core-h2>
```

File: pages/index.vue [hunk 4]
```diff
@@ -48,17 +48,13 @@
...
         <landing-img-swiper />
 
-        <i18n-page-wrapper
-            custom-x
-            custom-y
-            class="py-12 px-4 sm:px-10 md:px-12 lg:px-20 bg-blue-primary"
-        >
-            <h1 class="bulletin-title">{{ $t('bulletinList') }}</h1>
+        <div class="bulletin-section">
+            <core-h2 :sub-title="$t('bulletinList')" bulletin-color></core-h2>
```
Comment (flynnhou) [inline pages/index.vue:52]:
```suggestion
            <core-h2 :title="$t('bulletinList')" bulletin-color></core-h2>
```

**Review by flynnhou — CHANGES_REQUESTED** [review]

**Comment by flynnhou** [comment]
@yuyanghh Thanks for submitting the PR!

A few things to point out here:
1. The hover effect should only apply to the ones having links to navigate to. Blocks like room, break, etc. shouldn't change the background color for they're meant to be static.
2. I'm curious about if the media query could be replaced by [pointer events](https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent), e.g., `pointerenter`? Utilize such events to toggle the classes, and then define the hover style in css selectors with the classes so that we don't need to specify the media query. It looks a bit ad hoc and wet to me. But if pointer events don't work as you wanted, then let's leave it like this.

File: components/core/titles/LandingH2.vue (hunk 1 above)
Comment (linooohon) [reply components/core/titles/LandingH2.vue]: I agree with you!

File: components/core/titles/LandingH2.vue (hunk 2 above)
Comment (linooohon) [reply components/core/titles/LandingH2.vue]: I fixed it, thanks for the advice.

**Comment by linooohon** [comment]
Fixed @flynnhou what was suggested, and also did a force push.

**Review by flynnhou — APPROVED** [review]
lgtm
